import { callAIForJSON } from './aiRouter';
import { logger } from '../utils/logger';
import type { TopicSuggestion } from '../types';

export async function generateTopicSuggestions(): Promise<TopicSuggestion[]> {
  const system =
    'You are a developer-content strategist. You return JSON only — no explanation, no markdown.';

  const user = `Suggest 5 trending developer tutorial topics right now.
Focus on: React, Angular, AI tools, TypeScript, DevOps, Next.js, modern frontend.
Return JSON only with this exact shape:
{
  "topics": [
    {
      "title": "string (concrete, specific topic)",
      "hook": "string (one-line hook that grabs attention)",
      "difficulty": "beginner|intermediate|advanced",
      "estimatedDuration": number (seconds, between 60 and 1500),
      "whyTrending": "string (one sentence explaining current relevance)"
    }
  ]
}
Rules: exactly 5 topics, mix of difficulty levels, no markdown, no commentary.`;

  const { data, provider } = await callAIForJSON<{ topics: TopicSuggestion[] } | TopicSuggestion[]>({
    systemPrompt: system,
    userPrompt: user,
    temperature: 0.85,
    maxTokens: 2000,
  });
  logger.info(`Topics generated by: ${provider}`);

  const topics: TopicSuggestion[] = Array.isArray(data) ? data : data.topics;
  if (!topics || topics.length === 0) throw new Error('AI returned no topics.');

  return topics.slice(0, 5).map((t) => ({
    title: t.title,
    hook: t.hook,
    difficulty: t.difficulty,
    estimatedDuration: Math.max(30, Math.min(1800, Math.round(t.estimatedDuration || 180))),
    whyTrending: t.whyTrending,
  }));
}
